### ISSUE TITLE
Allow the default value of `include_xyz?` to be specified easily

### ISSUE THREAD

**Issue by GavinJoyce** [RestPack/restpack_serializer#116]
It's currently possible to do `serializer.as_json(model, { include_description?: false })` which will exclude the `description` attribute. The default is to include the description.

It would be nice to be able to easily set the default to **not include** the attribute. Something like:

```ruby
class PersonSerializer
    include RestPack::Serializer
    attributes :id, :name, { description: { include_by_default: false } }
end
```

`serializer.as_json(model)` would exclude the description
`serializer.as_json(model, { include_description?: false })` would exclude the description
`serializer.as_json(model, { include_description?: true })` would include the description

**Comment by GavinJoyce** [comment]
@eugeneius, how about:

```ruby
class PersonSerializer
    include RestPack::Serializer

    attributes :id, :name
    optional_attributes :description
end
```

**Comment by eugeneius** [comment]
Flagging them with a separate call definitely reads better than doing it as part of `attributes` :+1:

**Comment by eugeneius** [comment]
What about using a similar API to [mutations](https://github.com/cypriss/mutations):

```ruby
class PersonSerializer
  include RestPack::Serializer

  attributes :id, :name

  optional do
    attributes :description
  end
end
```

**Comment by GavinJoyce** [comment]
That's nice however I think if I added support for that, the main API should become:

```ruby
class PersonSerializer
  include RestPack::Serializer

  required do
    attributes :id, :name
  end

  optional do
    attributes :description
  end
end
```

I think I'll keep it simple for now, I've almost got a PR
